# One Hot encoder 예제


In [2]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [7]:
data =  {'Color' : ['red', 'green', 'blue', 'brown', 'black']}
df = pd.DataFrame(data)
print("원본")
df

원본


pandas.core.series.Series

In [5]:
# pandas의 get_dummies 함수를 사용한 원핫 인코딩

one_hot_encoded_df = pd.get_dummies(df, columns=['Color'], dtype='int')
print("원핫 인코딩 결과")
one_hot_encoded_df


원핫 인코딩 결과


Color_black  Color_blue  Color_brown  Color_green  Color_red
0            0           0            0            0          1
1            0           0            0            1          0
2            0           1            0            0          0
3            0           0            1            0          0
4            1           0            0            0          0

In [21]:
# sklearn의 OneHotEncoder를 사용한 원핫 인코딩

encoder = OneHotEncoder(sparse_output=False) #

# sklearn은 2차원 배열의 형태로 받게끔 설계
one_hot_encoded = encoder.fit_transform(df[['Color']]) 
print("sklearn의 OneHotEncoder 결과")
print(one_hot_encoded)
type(one_hot_encoded) # numpy.ndarray : 넘파이의 n-demensional array # 파이썬과 달리 모든 요소가 같은 타입이라 더 효과적

one_hot_encoded_df_sklearn = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out()) #인코딩된 데이터의 컬럼 이름
print("sklearn의 OneHotEncoder 결과")
one_hot_encoded_df_sklearn

## 데이터 프레임으로 바꾸는 이유는 그냥 조작의 편의성 때문




sklearn의 OneHotEncoder 결과
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
sklearn의 OneHotEncoder 결과


Color_black  Color_blue  Color_brown  Color_green  Color_red
0          0.0         0.0          0.0          0.0        1.0
1          0.0         0.0          0.0          1.0        0.0
2          0.0         1.0          0.0          0.0        0.0
3          0.0         0.0          1.0          0.0        0.0
4          1.0         0.0          0.0          0.0        0.0

In [23]:
# CountVectorizer 예제

from sklearn.feature_extraction.text import CountVectorizer # 자연어 처리시 자주 사용

genre = [
  'Action, Adventure, Fantasy',
  'Adventure, Fantasy, Action',
  'Action, Adventure, Crime',
  'Action, Crime, Drama',
  'Action Adventure, ScienceFiction',
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(genre)

df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
df

action  adventure  crime  drama  fantasy  sciencefiction
0       1          1      0      0        1               0
1       1          1      0      0        1               0
2       1          1      1      0        0               0
3       1          0      1      1        0               0
4       1          1      0      0        0               1